spring:
  datasource:
    url: jdbc:mysql://localhost:60256/practice_db
    username: testuser
    password: test123
    hikari:
      connection-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: debezium-app

## Source Database Properties
customer:
  datasource:
    host: localhost
    port: 60255
    database: practice_db
    username: testuser
    password: test123

  ## Logging properties
logging:
  level:
    root: INFO
    io:
      debezium:
        mysql:
          BinlogReader: INFO
    com:
      baeldung:
        libraries:
          debezium: DEBUG